# Generated by Django 3.1.3 on 2020-11-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_auto_20201118_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='orgnizer',
            new_name='organizer',
        ),
    ]
